# -*- coding: utf-8 -*-
"""astroresearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DoJD2sg7vE9ONbUze8sYAa5AwtMX6hVO
"""

pip install astroquery

"""**QUERY AN OBJECT:**

- set up query by giving and infinite row limit and defining which catalog

- define the radius starting with 20 arcsec to 60 arcsec (1 arcmin)

- find the object

I will set up the df with all the addresses.
Then I will make a list of those addresses so I can iterate through each whatever and put it into the function.

The function will then access vizier and search up all these addresses. I basically want to find which 2 parallaxes from all the results are closest to the parallax of the given star.
"""

import datetime
from google.colab import files
import pandas as pd
from astroquery.vizier import Vizier
from astropy.coordinates import SkyCoord
import astropy.units as u
import numpy as np

# Upload the Excel file
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)

def clean_dec(dec_val):
    try:
        if isinstance(dec_val, pd.Timedelta):
            total_seconds = dec_val.total_seconds()
        else:
            total_seconds = pd.to_timedelta(str(dec_val)).total_seconds()

        sign = '-' if total_seconds < 0 else '+'
        abs_seconds = abs(total_seconds)

        deg = int(abs_seconds // 3600)
        minutes = int((abs_seconds % 3600) // 60)
        seconds = int(abs_seconds % 60)

        return f"{sign}{deg:02}:{minutes:02}:{seconds:02}"
    except Exception:
        return str(dec_val).strip()

df["Dec"] = df["Dec"].apply(clean_dec)
df["plx"] = df["plx"].astype(str).str.strip()
df = df.dropna()
df.rename(columns=lambda x: x.strip(), inplace=True)

def format_coordinates(ra, dec):
    if isinstance(ra, datetime.time):
        ra = f"{ra.hour:02}:{ra.minute:02}:{ra.second:02}"
    if isinstance(dec, str):
        dec = dec.strip().replace("++", "")
        if not dec.startswith("-") and not dec.startswith("+"):
            dec = "+" + dec
    return ra, dec

stars_with_two_matches = []

def find_closest_parallax(ra_sexagesimal, dec_sexagesimal, star_parallax, index):
    coord = SkyCoord(ra_sexagesimal, dec_sexagesimal, unit=(u.hourangle, u.deg), frame='icrs')
    print(f"Processing coordinates: RA (deg) = {coord.ra.degree:.4f}, Dec (deg) = {coord.dec.degree:.4f}")

    Vizier.ROW_LIMIT = -1
    catalog = "I/355/gaiadr3"
    vizier = Vizier(columns=["Source", "RA_ICRS", "DE_ICRS", "Plx", "pmRA", "pmDE"])
    radius = 60 * u.arcsec

    result = vizier.query_region(coord, radius=radius, catalog=catalog)

    if len(result) > 0:
        data = result[0]

        filtered_stars = []
        for row in data:
            if row["Plx"] is None or row["pmRA"] is None or row["pmDE"] is None:
                continue

            star_coord = SkyCoord(ra=row["RA_ICRS"]*u.deg, dec=row["DE_ICRS"]*u.deg)
            sep = coord.separation(star_coord).arcsecond

            # Skip the original star (within 1 arcsec of the query coord)
            if sep < 1:
                continue

            parallax_diff = abs(row["Plx"] - star_parallax)
            if parallax_diff <= 2.5:
                filtered_stars.append({
                    "Source": row["Source"],
                    "Plx": row["Plx"],
                    "Parallax_Diff": parallax_diff,
                    "pmRA": row["pmRA"],
                    "pmDE": row["pmDE"]
                })

        if filtered_stars:
            filtered_stars.sort(key=lambda x: x["Parallax_Diff"])

            if len(filtered_stars) >= 2:
                stars_with_two_matches.append(index)

            print("\nClosest stars (within ±2.5 mas and not self-match):")
            for star in filtered_stars[:2]:
                print(f"Source ID: {star['Source']}, Parallax: {star['Plx']} mas, "
                      f"ΔPlx: {star['Parallax_Diff']:.3f} mas, "
                      f"Proper Motion (RA, Dec): ({star['pmRA']}, {star['pmDE']}) mas/yr")
        else:
            print("No stars found within ±2.5 mas of the target parallax.")
    else:
        print("No results found!")

for index, row in df.iterrows():
    try:
        ra = row['RA']
        dec = row['Dec']
        plx = row['plx']
        PMra = row.get('PMRA', 'N/A')
        PMdec = row.get('PMDEC', 'N/A')

        print(f"\nStar {index}: RA = {ra}, Dec = {dec}, Parallax = {plx}, pmRA = {PMra}, pmDEC = {PMdec}")

        ra, dec = format_coordinates(ra, dec)
        star_parallax = float(str(plx).split()[0])

        find_closest_parallax(ra, dec, star_parallax, index)

    except Exception as e:
        print(f"Skipping star at index {index} due to error: {e}")

print("\nStars that had two nearby matches within ±2.5 mas (excluding self):")
print(stars_with_two_matches)

import datetime
from google.colab import files
import pandas as pd
from astroquery.vizier import Vizier
from astropy.coordinates import SkyCoord
import astropy.units as u
import numpy as np

# Upload the Excel file
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)

def clean_dec(dec_val):
    try:
        if isinstance(dec_val, pd.Timedelta):
            total_seconds = dec_val.total_seconds()
        else:
            total_seconds = pd.to_timedelta(str(dec_val)).total_seconds()

        sign = '-' if total_seconds < 0 else '+'
        abs_seconds = abs(total_seconds)

        deg = int(abs_seconds // 3600)
        minutes = int((abs_seconds % 3600) // 60)
        seconds = int(abs_seconds % 60)

        return f"{sign}{deg:02}:{minutes:02}:{seconds:02}"
    except Exception:
        return str(dec_val).strip()

df["Dec"] = df["Dec"].apply(clean_dec)
df["plx"] = df["plx"].astype(str).str.strip()
df = df.dropna()
df.rename(columns=lambda x: x.strip(), inplace=True)

def format_coordinates(ra, dec):
    if isinstance(ra, datetime.time):
        ra = f"{ra.hour:02}:{ra.minute:02}:{ra.second:02}"
    if isinstance(dec, str):
        dec = dec.strip().replace("++", "")
        if not dec.startswith("-") and not dec.startswith("+"):
            dec = "+" + dec
    return ra, dec

stars_with_two_matches = []

def find_closest_parallax(ra_sexagesimal, dec_sexagesimal, star_parallax, index):
    coord = SkyCoord(ra_sexagesimal, dec_sexagesimal, unit=(u.hourangle, u.deg), frame='icrs')
    print(f"Processing coordinates: RA (deg) = {coord.ra.degree:.4f}, Dec (deg) = {coord.dec.degree:.4f}")

    Vizier.ROW_LIMIT = -1
    catalog = "I/355/gaiadr3"
    vizier = Vizier(columns=["Source", "RA_ICRS", "DE_ICRS", "Plx", "pmRA", "pmDE"])
    radius = 60 * u.arcsec

    result = vizier.query_region(coord, radius=radius, catalog=catalog)

    if len(result) > 0:
        data = result[0]

        filtered_stars = []
        for row in data:
            if row["Plx"] is None or row["pmRA"] is None or row["pmDE"] is None:
                continue

            star_coord = SkyCoord(ra=row["RA_ICRS"]*u.deg, dec=row["DE_ICRS"]*u.deg)
            sep = coord.separation(star_coord).arcsecond

            if sep < 1:
                continue  # Skip the original star

            parallax_diff = abs(row["Plx"] - star_parallax)
            if parallax_diff <= 2.5:
                filtered_stars.append({
                    "Source": row["Source"],
                    "RA_ICRS": row["RA_ICRS"],
                    "DE_ICRS": row["DE_ICRS"],
                    "Plx": row["Plx"],
                    "Parallax_Diff": parallax_diff,
                    "pmRA": row["pmRA"],
                    "pmDE": row["pmDE"]
                })

        if filtered_stars:
            filtered_stars.sort(key=lambda x: x["Parallax_Diff"])

            if len(filtered_stars) >= 2:
                stars_with_two_matches.append(index)

            print("\nClosest stars (within ±2.5 mas and not self-match):")
            for star in filtered_stars[:2]:
                star_coord = SkyCoord(ra=star['RA_ICRS'] * u.deg, dec=star['DE_ICRS'] * u.deg)
                ra_str = star_coord.ra.to_string(unit=u.hourangle, sep=':', precision=0, pad=True)
                dec_str = star_coord.dec.to_string(sep=':', precision=0, alwayssign=True, pad=True)

                print(f"RA: {ra_str}, Dec: {dec_str}, "
                      f"Parallax: {star['Plx']} mas, ΔPlx: {star['Parallax_Diff']:.3f} mas, "
                      f"Proper Motion (RA, Dec): ({star['pmRA']}, {star['pmDE']}) mas/yr")
        else:
            print("No stars found within ±2.5 mas of the target parallax.")
    else:
        print("No results found!")

for index, row in df.iterrows():
    try:
        ra = row['RA']
        dec = row['Dec']
        plx = row['plx']
        PMra = row.get('PMRA', 'N/A')
        PMdec = row.get('PMDEC', 'N/A')

        print(f"\nStar {index}: RA = {ra}, Dec = {dec}, Parallax = {plx}, pmRA = {PMra}, pmDEC = {PMdec}")

        ra, dec = format_coordinates(ra, dec)
        star_parallax = float(str(plx).split()[0])

        find_closest_parallax(ra, dec, star_parallax, index)

    except Exception as e:
        print(f"Skipping star at index {index} due to error: {e}")

print("\nStars that had two nearby matches within ±2.5 mas (excluding self):")
print(stars_with_two_matches)